name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verificar archivos base
        run: |
          test -f index.html
          test -f style.css
          test -f script.js
